In [1]:
import numpy as np

In [2]:
x = np.array([100,400,-50,-40])
y = np.array([10,15,20,25])
condition = np.array([True,True,False,False])

# bad approach
z = [a if cond else b for a,cond,b in zip(x,condition,y)]
print(z)

[100, 400, 20, 25]


In [3]:
# good approach
z2 = np.where(condition,x,y)
print(z2)

[100 400  20  25]


In [4]:
z3 = np.where(x>0,1,x)
print(z3)

[  1   1 -50 -40]


In [5]:
print(x.sum())

410


In [6]:
x2 = np.array([[1,2],[3,4]])
print(x2)

[[1 2]
 [3 4]]


In [7]:
print(x2.sum(axis = 0))   # along column
print(x2.sum(axis = 1))   # along row

[4 6]
[3 7]


In [8]:
print(x.mean())
print(x.std())
print(x.var())

102.5
181.71062159378576
33018.75


In [9]:
condition2 = np.array([True,False,True])
print(condition2.any())   # or
print(condition2.all())   # and

True
False


In [10]:
unsorted = np.array([1,5,2,9,76,45,78,91])
print(unsorted)
unsorted.sort()       # in ascending order
print(unsorted)

[ 1  5  2  9 76 45 78 91]
[ 1  2  5  9 45 76 78 91]


In [11]:
arr2 = np.array(['liquid','liquid','liquid','gas','gas','solid','solid'])
print(np.unique(arr2))

['gas' 'liquid' 'solid']


In [12]:
print(np.in1d(['solid','liquid','plasma'],arr2))

[ True  True False]
