In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
# when we have a large dataset, memory blocks can occur during the execution of the code, when it occurs all the arrays are deleted from the memory, so we need to save our arrays to handle this issue

In [4]:
np.save("saved_array", arr)

In [5]:
load_array1 = np.load("saved_array.npy")
print(load_array1)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
arr2 = np.arange(25)
arr3 = np.arange(5)

np.savez("saved_archive.npz", x=arr2, y=arr3)

In [8]:
load_npz = np.load("saved_archive.npz")
print(load_npz['x'])
print(load_npz['y'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[0 1 2 3 4]


In [9]:
np.savetxt("myarray.txt", arr2, delimiter=',')

In [10]:
load_txt = np.loadtxt("myarray.txt", delimiter=',')
print(load_txt)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24.]


In [11]:
 # delimiter is used to seperate values from each other