In [1]:
import numpy as np

In [2]:
arr = np.arange(100,160,2)
print(arr)

[100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]


In [3]:
# indexes are used to access the required elements of the array

In [6]:
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[4])

100
102
104
108


In [7]:
print(arr[0:5:1])

[100 102 104 106 108]


In [9]:
# updating elements
arr[0:5] = 0
print(arr)

[  0   0   0   0   0 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]


In [11]:
arr2 = arr[4:10]
print(arr2)

arr2[:] = 1
print(arr2)

[  0 110 112 114 116 118]
[1 1 1 1 1 1]


In [14]:
print(arr) 
# this should not happen, as changes were not made in arr, instead changes were made in arr2
# this happened because whenever slicing is done, no extra memory is allocated, so arr2 doesnot have memory location of its own, its pointing to the memory location of arr only.
# saves memory in large datasets

[  0   0   0   0   1   1   1   1   1   1 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]


In [15]:
arr3 = arr.copy()
print(arr3)

[  0   0   0   0   1   1   1   1   1   1 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]


In [16]:
arr3[:] = 0

In [17]:
print(arr3)
print(arr)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[  0   0   0   0   1   1   1   1   1   1 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158]
