In [1]:
import numpy as np

In [4]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
print(arr2d[0])
print(arr2d[1])

[1 2 3]
[4 5 6]


In [7]:
print(arr2d[0][0])

1


In [8]:
print(arr2d[1][2])

6


In [9]:
slice1 = arr2d[0:1,0:2]
print(slice1)

[[1 2]]


In [10]:
slice2 = arr2d[0:2,0:3]
print(slice2)

[[1 2 3]
 [4 5 6]]


In [11]:
slice3 = arr2d[:2,:3]
print(slice3)

[[1 2 3]
 [4 5 6]]


In [12]:
slice4 = arr2d[1:,2:]
print(slice4)

[[6]
 [9]]


In [14]:
arr_len = arr2d.shape
print(arr_len)
n_rows = arr_len[0]
print(n_rows)

(3, 3)
3


In [15]:
for i in range(n_rows):
    arr2d[i][0] = i
    
print(arr2d)

[[0 2 3]
 [1 5 6]
 [2 8 9]]


In [18]:
# accessing rows
print(arr2d[[0,1]])
print(arr2d[[1,0]])

[[0 2 3]
 [1 5 6]]
[[1 5 6]
 [0 2 3]]
