In [1]:
import numpy as np

In [2]:
mylist1 = [101,102,103]
myArray = np.array(mylist1)
print(myArray)

[101 102 103]


In [4]:
mylist2 = [201,202,203]
myArray2D = np.array([mylist1,mylist2])
print(myArray2D)

[[101 102 103]
 [201 202 203]]


In [6]:
print(myArray.shape)
print(myArray2D.shape)

(3,)
(2, 3)


In [9]:
print(myArray.dtype)
print(myArray2D.dtype)

int32
int32


In [13]:
zero_array = np.zeros(5)
print(zero_array)

zero_array2D = np.zeros([5,5])
print(zero_array2D)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
zero_array = np.ones(5)
print(zero_array)

zero_array2D = np.ones([5,5])
print(zero_array2D)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
# creates array with junk values, faster than the above two, creates array with different values everytime
zero_array = np.empty(5)
print(zero_array)

zero_array2D = np.empty([5,5])
print(zero_array2D)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [18]:
identity_array = np.eye(3)
print(identity_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
# the aboves are used in statistical analysis too

In [22]:
ap_array = np.arange(0,50,2)
print(ap_array)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]


In [23]:
# all above are used to do high performance statistical mathematics