In [1]:
import numpy as np

In [4]:
A = np.arange(15)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [6]:
B = np.arange(5,10)
print(B)

[5 6 7 8 9]


In [7]:
C = np.arange(5,10,2)
print(C)

[5 7 9]


In [8]:
D = np.sqrt(A)
print(D)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479
 3.46410162 3.60555128 3.74165739]


In [9]:
E = np.exp(A)
print(E)

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04
 1.62754791e+05 4.42413392e+05 1.20260428e+06]


In [11]:
F = np.random.randn(5)
print(F)
F = np.random.randn(5,5)
print(F)

[ 0.108785   -0.09799078  1.37454766  1.05407525  0.42044455]
[[-0.37173366  1.3494277   0.05382826 -0.90683041 -1.12238054]
 [-0.49941121  1.35974607 -1.38186634 -0.79642976 -0.7556958 ]
 [ 0.4749306  -0.32237092 -0.81053267  0.06453616 -0.80085797]
 [ 0.22311344 -1.05679456 -0.72378184  0.21543714  0.75174747]
 [ 0.23292451 -0.62213927 -0.06512033  0.15428429 -0.06273669]]


In [12]:
print(A)
print(D)
G = np.add(A,D)
print(G)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479
 3.46410162 3.60555128 3.74165739]
[ 0.          2.          3.41421356  4.73205081  6.          7.23606798
  8.44948974  9.64575131 10.82842712 12.         13.16227766 14.31662479
 15.46410162 16.60555128 17.74165739]


In [13]:
A = np.array([1,5,7,10])
B = np.array([0,6,8,9])
H = np.maximum(A,B)
print(H)

[ 1  6  8 10]


In [14]:
# numpy.org , docs.scipy.org 