In [1]:
import numpy as np
import pandas as pd

In [2]:
A1 = np.arange(25).reshape(5,5)
B1 = np.random.randn(25).reshape(5,5)
print(A1)
print(B1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 2.63734358  0.33215463 -0.3799505  -0.2144006   0.71046519]
 [ 1.44623357  1.02962578  0.40563268  0.03202193 -0.79317648]
 [-0.13063586 -0.72927636 -1.22716909  0.80746876 -0.30249657]
 [-0.56482454 -0.69186541 -1.7187572   1.22345413  0.39201526]
 [ 2.03833253  0.07888102  1.12555672 -0.57389192  0.86020619]]


In [3]:
np.concatenate([A1, B1], axis=1)    #along column

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ,
         2.63734358,  0.33215463, -0.3799505 , -0.2144006 ,  0.71046519],
       [ 5.        ,  6.        ,  7.        ,  8.        ,  9.        ,
         1.44623357,  1.02962578,  0.40563268,  0.03202193, -0.79317648],
       [10.        , 11.        , 12.        , 13.        , 14.        ,
        -0.13063586, -0.72927636, -1.22716909,  0.80746876, -0.30249657],
       [15.        , 16.        , 17.        , 18.        , 19.        ,
        -0.56482454, -0.69186541, -1.7187572 ,  1.22345413,  0.39201526],
       [20.        , 21.        , 22.        , 23.        , 24.        ,
         2.03833253,  0.07888102,  1.12555672, -0.57389192,  0.86020619]])

In [4]:
np.concatenate([A1, B1], axis=0)     #along rows

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ],
       [ 5.        ,  6.        ,  7.        ,  8.        ,  9.        ],
       [10.        , 11.        , 12.        , 13.        , 14.        ],
       [15.        , 16.        , 17.        , 18.        , 19.        ],
       [20.        , 21.        , 22.        , 23.        , 24.        ],
       [ 2.63734358,  0.33215463, -0.3799505 , -0.2144006 ,  0.71046519],
       [ 1.44623357,  1.02962578,  0.40563268,  0.03202193, -0.79317648],
       [-0.13063586, -0.72927636, -1.22716909,  0.80746876, -0.30249657],
       [-0.56482454, -0.69186541, -1.7187572 ,  1.22345413,  0.39201526],
       [ 2.03833253,  0.07888102,  1.12555672, -0.57389192,  0.86020619]])

In [5]:
s1 = pd.Series([100,200,300], index=list('ABC'))
s2 = pd.Series([400,500], index=list('DE'))
print(s1)
print(s2)

A    100
B    200
C    300
dtype: int64
D    400
E    500
dtype: int64


In [6]:
pd.concat([s1,s2], axis=0)

A    100
B    200
C    300
D    400
E    500
dtype: int64

In [7]:
pd.concat([s1,s2], axis=1)

0      1
A  100.0    NaN
B  200.0    NaN
C  300.0    NaN
D    NaN  400.0
E    NaN  500.0

In [11]:
s1 = s1.reset_index(drop=True)

In [12]:
s2 = s2.reset_index(drop=True)

In [13]:
pd.concat([s1,s2], axis=1)

0      1
0  100  400.0
1  200  500.0
2  300    NaN

In [14]:
df1 = pd.DataFrame(np.random.randn(12).reshape(4,3), columns=list('ABC'))
df2 = pd.DataFrame(np.arange(9).reshape(3,3), columns=list('ABD'))
print(df1)
print(df2)

          A         B         C
0  0.146659  0.091204 -0.302387
1  1.636661  0.031478  0.528431
2 -0.675996 -0.771361  0.599547
3  0.091373  1.113592  1.188181
   A  B  D
0  0  1  2
1  3  4  5
2  6  7  8


In [15]:
pd.concat([df1,df2], axis=0)

A         B         C    D
0  0.146659  0.091204 -0.302387  NaN
1  1.636661  0.031478  0.528431  NaN
2 -0.675996 -0.771361  0.599547  NaN
3  0.091373  1.113592  1.188181  NaN
0  0.000000  1.000000       NaN  2.0
1  3.000000  4.000000       NaN  5.0
2  6.000000  7.000000       NaN  8.0

In [17]:
pd.concat([df1,df2], axis=0, ignore_index=True)

A         B         C    D
0  0.146659  0.091204 -0.302387  NaN
1  1.636661  0.031478  0.528431  NaN
2 -0.675996 -0.771361  0.599547  NaN
3  0.091373  1.113592  1.188181  NaN
4  0.000000  1.000000       NaN  2.0
5  3.000000  4.000000       NaN  5.0
6  6.000000  7.000000       NaN  8.0

In [18]:
pd.concat([df1,df2], axis=1, ignore_index=True)

0         1         2    3    4    5
0  0.146659  0.091204 -0.302387  0.0  1.0  2.0
1  1.636661  0.031478  0.528431  3.0  4.0  5.0
2 -0.675996 -0.771361  0.599547  6.0  7.0  8.0
3  0.091373  1.113592  1.188181  NaN  NaN  NaN