In [3]:
import numpy as np
import pandas as pd # high level data manipulation tool, biuld on top of numpy and extends the functionality of numpy. it has 2 DS:- series and dataframes

In [4]:
# series - 1D labelled array capable of holding data of any type, here indexes can be numerical or character lables, which was not in numpy, there index was only numerical

In [5]:
s1 = pd.Series([5,10,15,20])
print(s1)

0     5
1    10
2    15
3    20
dtype: int64


In [6]:
print(s1.values)

[ 5 10 15 20]


In [7]:
print(s1.index.values)

[0 1 2 3]


In [8]:
revenue_array = np.array([400,300,200,100])
print(revenue_array)

[400 300 200 100]


In [10]:
revenue_series = pd.Series(revenue_array)
print(revenue_series)

0    400
1    300
2    200
3    100
dtype: int32


In [11]:
revenue = pd.Series(revenue_array, index=['uber','ola','lyft','gojek'])
print(revenue)

uber     400
ola      300
lyft     200
gojek    100
dtype: int32


In [12]:
revenue['ola']

300

In [13]:
revenue['gojek']

100

In [14]:
print(revenue[revenue>250])

uber    400
ola     300
dtype: int32


In [15]:
print('ola' in revenue)

True


In [16]:
print('grab' in revenue)

False


In [17]:
revenue_dict = revenue.to_dict()
print(revenue_dict)

{'uber': 400, 'ola': 300, 'lyft': 200, 'gojek': 100}


In [18]:
print(revenue)

uber     400
ola      300
lyft     200
gojek    100
dtype: int32


In [23]:
print(revenue + revenue)

uber     800
ola      600
lyft     400
gojek    200
dtype: int32


In [25]:
revenue.name = "Company - Revenue"
revenue.index.name = "Company Names"
print(revenue)

Company Names
uber     400
ola      300
lyft     200
gojek    100
Name: Company - Revenue, dtype: int32
